name:                0nine-functors
version:             0.1.0.0
github:              "Levisoto/0nine-functors"
license:             BSD3
author:              "Levi Soto"
maintainer:          "levisoto.337@gmail.com"
copyright:           "2018 Levi Soto"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/Levisoto/0nine-functors#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  0nine-functors-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - 0nine-functors

tests:
  0nine-functors-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - 0nine-functors
